kind = "api"
previewPath = "/api"
title = "DialogAI API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "python main.py"

[services.production]

[services.production.build]
args = ["python", "-m", "compileall", "."]

[services.production.run]
args = ["python", "main.py"]

[services.production.run.env]
PORT = "8080"
PYTHONUNBUFFERED = "1"

[services.production.health.startup]
path = "/api/healthz"
